spring:
  application:
    name: cloud-provider-movie
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率值介于0~1之间，1表示全部采样
        probability: 0.8
server:
  port: 8000
# 指定注册到哪个注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #注册自己服务使用ip的方式

